class ICONS :
    battery_plugged = ''
    battery1 = ''
    battery2 = ''
    battery3 = ''
    battery4 = ''
    signal0 = ''
    signal1 = ''
    signal2 = ''
    signal3 = ''
    signal4 = ''
    play=''
    pause=''
