#! /usr/bin/env python3
import subprocess
from utils import translate
import re
import os

ICONS = ['', '', '']
ICON_MUTE = ''

def setVol(vol):
    CMD = ['amixer', 'set', 'Master', vol]
    output = subprocess.Popen( CMD, stdout=subprocess.PIPE ).communicate()

if __name__ == "__main__":
    if os.environ['BLOCK_BUTTON'] == '4':
        setVol("5%+")
    elif os.environ['BLOCK_BUTTON'] == '1':
        setVol("toggle")
    elif os.environ['BLOCK_BUTTON'] == '5':
        setVol("5%-")

    CMD = ['amixer', 'get', 'Master']
    output = subprocess.Popen( CMD, stdout=subprocess.PIPE ).communicate()
    audio_data = str(output)

    re_vol_pattern = re.compile("\[(?P<vol>[0-9]{1,3})%\]")
    vol = int(re_vol_pattern.findall(audio_data)[0])

    re_state_pattern = re.compile("\[(on|off)\]")
    state = str(re_state_pattern.findall(audio_data)[0])
    
    i = int(translate(vol, 0, 70, 0, 2 ))
    icon = ICONS[i]

    if state == "off": 
        icon = ICONS[0]
        vol = 'off'
    
    print(icon, vol)
