#!/usr/bin/env python3

import alsaaudio
import os
from utils import translate

MIXERS = []
ICONS = ['', '', '', '']
ICON_MUTE = ''
VOL_OUT=''
ICON=ICONS[0]

def decrVolume(v):
    vol = MIXERS[0].getvolume()[0]
    n = 0 if vol - v < 0 else vol - v
    for m in MIXERS:
        m.setvolume(n)

def incrVolume(v):
    vol = MIXERS[0].getvolume()[0]
    n = 100 if vol + v > 100 else vol + v
    for m in MIXERS:
        m.setvolume(n)

def getVol():
    vol = MIXERS[0].getvolume()[0]
    return vol

def toggle():
    try:
        for m in MIXERS:
            if getMute():
                m.setmute(0)
            else :
                m.setmute(1)
    except:
        decrVolume(100)

def getMute():
    try:
        return MIXERS[0].getmute()[0] == 1
    except:
        return False

if __name__ == "__main__":
    DEFAULT_MIXER = os.getenv("BLOCK_INSTANCE", '')
    if DEFAULT_MIXER == '':
        MIXERS.append(alsaaudio.Mixer("Master"))
    else:
        mixers_names = os.environ['BLOCK_INSTANCE'].split("|")
        for m in mixers_names:
            M1 = alsaaudio.Mixer(m)
            MIXERS.append(M1)
    
    BUTTON = os.getenv('BLOCK_BUTTON', default=None)

    if BUTTON == '1':
        toggle()
    elif BUTTON == '4':
        incrVolume(5)
    elif BUTTON == '5':
        decrVolume(5)
    
    vol = getVol()
    if getMute():
        print("%s %s" % (ICON_MUTE, vol))
    else:
        i = int(translate(vol, 0, 100, 0, len(ICONS)-1))
        ICON = ICON_MUTE if getMute() else  ICONS[i]
        print("%s %s" % (ICON, vol))
