#! /usr/bin/env python3

import sys
import os
from datetime import datetime

import psutil

from utils import icons
from utils.helpers import translate
from Modules.Axp288 import Axp288


ICONS = [
  icons.ICONS.battery1,
  icons.ICONS.battery2,
  icons.ICONS.battery3,
  icons.ICONS.battery4,
]

if __name__ == '__main__':

  BATTERY = psutil.sensors_battery()
  if BATTERY == None:
      BATTERY = Axp288()
  
  BUTTON = os.getenv("BLOCK_BUTTON", '')

  plugged = BATTERY.power_plugged
  percent = int(BATTERY.percent)
  
  if BUTTON == '1':
    print(percent)
    sys.exit(0)

  if BATTERY.power_plugged: 
    icon = icons.ICONS.battery_plugged
  else:
    i = round(translate(percent, 0, 100, 0, len(ICONS)-1))
    icon = ICONS[i]
    now = datetime.now()
    second = int(now.strftime("%S"))
    if percent < 10 and (second % 2)  == 0:
      icon = '  '

  print(icon)
