#! /usr/bin/env python3

import psutil
from Modules.Axp288 import Axp288
battery = psutil.sensors_battery()
if battery == None:
    battery = Axp288()
plugged = battery.power_plugged
percent = int(battery.percent)

if battery.power_plugged: 
  icon = ''
else:
  icon = ''

print(icon, percent)
