#!/usr/bin/env python3

from itertools import islice
from time import time, strftime, gmtime
import os
import math
import mpd

from utils.icons import ICONS

HOST_PORT = os.getenv('BLOCK_INSTANCE', 'localhost:6600')
HOST, PORT = HOST_PORT.split(":") 

BUTTON = os.getenv('BLOCK_BUTTON', '0')

if BUTTON == "":
    BUTTON = '0'

def toggleplay(state, c):
    if state == 'play':
        c.pause()
    else:
        c.play()

def command(button, state, c):
    if button == 1:
        c.previous()
    elif button == 2:
        toggleplay(state, c)
    elif button == 3:
        c.next()

def formatTime(current_time, total_time):
    show_current_time = strftime("%M:%S", gmtime(int(current_time)))
    show_total_time = strftime("%M:%S", gmtime(int(total_time)))
    return " ".join((show_current_time, show_total_time))

def access_char(string, i):
    return string[i % len(string)]

def makeDisplay(title, album, current_time, size=20):
    strdisplay =  title + ' - ' +  album + (" " * int(size/2+5))
    end = int(int(current_time) * 3)
    return "".join([ access_char(strdisplay, i) for i in range(end-size, end)])

c = mpd.MPDClient()
c.connect(HOST, PORT)

status = c.status()

try:
    currentsong = c.currentsong()
    title, album = currentsong['title'], currentsong['album']

    current_time, total_time = status['time'].split(":")
    time_strig = formatTime(current_time, total_time)

    display = makeDisplay(title, album, current_time=current_time)
except: 
    current_time, total_time = '0', '0'
    time_strig = formatTime(current_time, total_time)
    title, album = "( ( ( ( stop ) ) ) )", ''
    display = makeDisplay(title, album, int(time()))

command(int(BUTTON), state=status['state'], c=c)

if status['state'] == 'play':
    icon = ICONS.pause
else:
    icon = ICONS.play

print(icon, display, time_strig)