#! /usr/bin/env python3.6

import subprocess
import re
import os
from utils.helpers import translate
from utils import icons 

ICONS = [
    icons.ICONS.signal0,
    icons.ICONS.signal1,
    icons.ICONS.signal2,
    icons.ICONS.signal3,
    icons.ICONS.signal4,
]

cmd = [ 'nmcli', 'device', 'wifi']
output = subprocess.Popen( cmd, stdout=subprocess.PIPE ).communicate()[0]

networks = str(output).split("\\n")[1:]

for n in networks:
    
    network_info = re.split('\s{2,9}', n)

    if(len(network_info) < 3):
        continue
    
    if network_info[0] == "*":
        ssid = network_info[1]
        signal = int(network_info[5])
        signal_index = round(translate(signal, 0, 100, 0 , len(ICONS) - 1))

        if os.environ['BLOCK_BUTTON'] == '1':
            print(ICONS[signal_index], "strength", signal)
        else: 
            print(ICONS[signal_index], ssid)
            print(ICONS [signal_index], ssid)

        break
    